-------------------------------------------------------------------------------
Test set: com.unrc.app.TestSuite
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.159 sec <<< FAILURE!
shouldValidateMandatoryFields(com.unrc.app.UserSpec)  Time elapsed: 0.158 sec  <<< ERROR!
org.javalite.activejdbc.InitException: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: NO)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:946)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:2870)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:812)
	at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:3269)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1182)
	at com.mysql.jdbc.Connection.createNewIO(Connection.java:2670)
	at com.mysql.jdbc.Connection.<init>(Connection.java:1531)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:266)
	at java.sql.DriverManager.getConnection(DriverManager.java:620)
	at java.sql.DriverManager.getConnection(DriverManager.java:200)
	at org.javalite.activejdbc.DB.open(DB.java:64)
	at org.javalite.activejdbc.Base.open(Base.java:51)
	at com.unrc.app.UserSpec.before(UserSpec.java:16)

shouldValidateMandatoryFields(com.unrc.app.UserSpec)  Time elapsed: 0.158 sec  <<< ERROR!
org.javalite.activejdbc.DBException: Cannot rollback transaction, connection 'default' not available
	at org.javalite.activejdbc.DB.rollbackTransaction(DB.java:587)
	at org.javalite.activejdbc.Base.rollbackTransaction(Base.java:296)
	at com.unrc.app.UserSpec.after(UserSpec.java:22)

